#include "src/game/envfx_snow.h"

const GeoLayout castle_grounds_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_FORCE, castle_grounds_dl_AABGMain_001_mesh_layer_0),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_AANoCullAlphaMesh_mesh),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_AANoCullAlphaMesh_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, castle_grounds_dl_AANoCullLayer6_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_beanstalk_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 2635, 9565, -271, castle_grounds_dl_CloudOcean_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_dockalpha_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_dockpillars_mesh),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, castle_grounds_dl_penishills_002_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_penishills_028_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_transparentsand_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_transparentsand_004_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -1406, -250, -2902, castle_grounds_dl_transparentwater_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_transparentzzfog_001_mesh),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_Zbeanstalk_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_zoo_002_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ZZZMain_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ZZZMain_mesh),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ZZZMain_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_ZZZMain_003_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_grounds_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, -26626, 0, 8109, -26626, -1, 8109, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_grounds_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_FORCE, castle_grounds_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, castle_grounds_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
