extern const GeoLayout vulcanboulderpart_geo[];
extern Lights1 vulcanboulderpart_f3d_material_009_layer1_lights;
extern u8 vulcanboulderpart_R_Fortress_0020_tex_i4[];
extern u8 vulcanboulderpart_mim_hachinosutif_rgba16[];
extern Vtx vulcanboulderpart_Circle_mesh_layer_1_vtx_0[60];
extern Gfx vulcanboulderpart_Circle_mesh_layer_1_tri_0[];
extern Gfx mat_vulcanboulderpart_f3d_material_009_layer1[];
extern Gfx mat_revert_vulcanboulderpart_f3d_material_009_layer1[];
extern Gfx vulcanboulderpart_Circle_mesh_layer_1[];
extern Gfx vulcanboulderpart_material_revert_render_settings[];
