extern const GeoLayout fallplatform2_geo[];
extern Lights1 fallplatform2_f3d_material_lights;
extern u8 fallplatform2_YIblock_ci4[];
extern u8 fallplatform2_YIblock_ci4_pal_rgba16[];
extern Vtx fallplatform2_Cube_003_mesh_layer_1_vtx_cull[8];
extern Vtx fallplatform2_Cube_003_mesh_layer_1_vtx_0[152];
extern Gfx fallplatform2_Cube_003_mesh_layer_1_tri_0[];
extern Gfx mat_fallplatform2_f3d_material[];
extern Gfx mat_revert_fallplatform2_f3d_material[];
extern Gfx fallplatform2_Cube_003_mesh_layer_1[];
extern Gfx fallplatform2_material_revert_render_settings[];
