extern const GeoLayout lavafloor_geo[];
extern Lights1 lavafloor_LAVAMAT_layer1_lights;
extern u8 lavafloor_jet_1_i4[];
extern u8 lavafloor__3543534_i4[];
extern Vtx lavafloor_LAVA_mesh_layer_1_vtx_0[64];
extern Gfx lavafloor_LAVA_mesh_layer_1_tri_0[];
extern Gfx mat_lavafloor_LAVAMAT_layer1[];
extern Gfx mat_revert_lavafloor_LAVAMAT_layer1[];
extern Gfx lavafloor_LAVA_mesh_layer_1[];
extern Gfx lavafloor_material_revert_render_settings[];
