#include "src/game/envfx_snow.h"

const GeoLayout bookend_part_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bookend_000_offset_002_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bookend_001_offset_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bookend_002_offset_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bookend_000_offset_004_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bookend_001_offset_001_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bookend_002_offset_002_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bookend_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
