extern const GeoLayout fishbone_geo[];
extern Lights1 fishbone_f3d_material_lights;
extern u8 fishbone_fishboneplatform_ci4[];
extern u8 fishbone_fishboneplatform_ci4_pal_rgba16[];
extern Vtx fishbone_Plane_mesh_layer_4_vtx_cull[8];
extern Vtx fishbone_Plane_mesh_layer_4_vtx_0[20];
extern Gfx fishbone_Plane_mesh_layer_4_tri_0[];
extern Gfx mat_fishbone_f3d_material[];
extern Gfx mat_revert_fishbone_f3d_material[];
extern Gfx fishbone_Plane_mesh_layer_4[];
extern Gfx fishbone_material_revert_render_settings[];
