extern const GeoLayout whalespout_geo[];
extern Lights1 whalespout_SpoutScroll_layer5_lights;
extern u8 whalespout__38_rgba16[];
extern u8 whalespout__28cce000_fmt0433_mip00_64x64_tm04_sw00000100_i4[];
extern Vtx whalespout_Circle_mesh_layer_5_vtx_0[31];
extern Gfx whalespout_Circle_mesh_layer_5_tri_0[];
extern Gfx mat_whalespout_SpoutScroll_layer5[];
extern Gfx mat_revert_whalespout_SpoutScroll_layer5[];
extern Gfx whalespout_Circle_mesh_layer_5[];
extern Gfx whalespout_material_revert_render_settings[];
