extern const GeoLayout aircruise_geo[];
extern Vtx aircruise_Bone_mesh_vtx_0[38];
extern Gfx aircruise_Bone_mesh_tri_0[];
extern Vtx aircruise_Bone_mesh_vtx_1[28];
extern Gfx aircruise_Bone_mesh_tri_1[];
extern Vtx aircruise_Bone_mesh_vtx_2[17];
extern Gfx aircruise_Bone_mesh_tri_2[];
extern Vtx aircruise_Bone_mesh_vtx_3[16];
extern Gfx aircruise_Bone_mesh_tri_3[];
extern Vtx aircruise_Bone_mesh_vtx_4[14];
extern Gfx aircruise_Bone_mesh_tri_4[];
extern Vtx aircruise_Bone_001_mesh_vtx_0[12];
extern Gfx aircruise_Bone_001_mesh_tri_0[];
extern Vtx aircruise_wing2_l_mesh_vtx_0[4];
extern Gfx aircruise_wing2_l_mesh_tri_0[];
extern Vtx aircruise_wing2_r_mesh_vtx_0[4];
extern Gfx aircruise_wing2_r_mesh_tri_0[];
extern Vtx aircruise_wing4_l_mesh_vtx_0[4];
extern Gfx aircruise_wing4_l_mesh_tri_0[];
extern Vtx aircruise_wing4_r_mesh_vtx_0[4];
extern Gfx aircruise_wing4_r_mesh_tri_0[];
extern Vtx aircruise_wwing2_l_mesh_vtx_0[4];
extern Gfx aircruise_wwing2_l_mesh_tri_0[];
extern Vtx aircruise_wwing2_r_mesh_vtx_0[4];
extern Gfx aircruise_wwing2_r_mesh_tri_0[];

extern Gfx aircruise_Bone_mesh[];
extern Gfx aircruise_Bone_001_mesh[];
extern Gfx aircruise_wing2_l_mesh[];
extern Gfx aircruise_wing2_r_mesh[];
extern Gfx aircruise_wing4_l_mesh[];
extern Gfx aircruise_wing4_r_mesh[];
extern Gfx aircruise_wwing2_l_mesh[];
extern Gfx aircruise_wwing2_r_mesh[];
extern Gfx aircruise_material_revert_render_settings[];

