#include "src/game/envfx_snow.h"

const GeoLayout jrb_area_6_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 76, -400, 24, jrb_dl_Circle_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 88, 30, -32, jrb_dl_Circle_022_mesh),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 1703, 2509, -916, 0, 27, 0, jrb_dl_Circle_042_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 109, -20, -34, jrb_dl_Circle_045_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 0, 481, 0, jrb_dl_nippercrowd_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 0, 2206, 0, jrb_dl_Plane_001_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 0, 416, 0, jrb_dl_spinningdiscs_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jrb_area_6[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, -21560, 3941, 1096, -21560, 3940, 1096, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, jrb_area_6_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, jrb_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jrb_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
