extern const GeoLayout spider_Bone_opt1[];
extern const GeoLayout spider_Bone_opt2[];
extern const GeoLayout spider_Bone_opt3[];
extern const GeoLayout spider_Bone_opt4[];
extern const GeoLayout spider_geo[];
extern Lights1 spider_f3d_material_004_lights;
extern Lights1 spider_f3d_material_005_lights;
extern Lights1 spider_f3d_material_006_lights;
extern Lights1 spider_f3d_material_007_lights;
extern Lights1 spider_f3d_material_008_lights;
extern u8 spider_frame1_ci4[];
extern u8 spider_frame1_ci4_pal_rgba16[];
extern u8 spider_frame2_ci4[];
extern u8 spider_frame2_ci4_pal_rgba16[];
extern u8 spider_frame3_ci4[];
extern u8 spider_frame3_ci4_pal_rgba16[];
extern u8 spider_frame4_ci4[];
extern u8 spider_frame4_ci4_pal_rgba16[];
extern u8 spider_frame5_ci4[];
extern u8 spider_frame5_ci4_pal_rgba16[];
extern Vtx spider_Bone_001_mesh_layer_4_vtx_0[4];
extern Gfx spider_Bone_001_mesh_layer_4_tri_0[];
extern Gfx mat_spider_f3d_material_004[];
extern Gfx mat_revert_spider_f3d_material_004[];
extern Gfx mat_spider_f3d_material_005[];
extern Gfx mat_revert_spider_f3d_material_005[];
extern Gfx mat_spider_f3d_material_006[];
extern Gfx mat_revert_spider_f3d_material_006[];
extern Gfx mat_spider_f3d_material_007[];
extern Gfx mat_revert_spider_f3d_material_007[];
extern Gfx mat_spider_f3d_material_008[];
extern Gfx mat_revert_spider_f3d_material_008[];
extern Gfx spider_Bone_001_mesh_layer_4[];
extern Gfx spider_Bone_001_mesh_layer_4_mat_override_f3d_material_005_0[];
extern Gfx spider_Bone_001_mesh_layer_4_mat_override_f3d_material_006_1[];
extern Gfx spider_Bone_001_mesh_layer_4_mat_override_f3d_material_007_2[];
extern Gfx spider_Bone_001_mesh_layer_4_mat_override_f3d_material_008_3[];
extern Gfx spider_material_revert_render_settings[];
