#include "src/game/envfx_snow.h"

const GeoLayout cheepcheepnew_geo[] = {
	GEO_CULLING_RADIUS(500),
	GEO_OPEN_NODE(),
		GEO_SCALE(LAYER_FORCE, 16384),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -13, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, cheepcheepnew_000_offset_001_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, cheepcheepnew_000_offset_002_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 135, 0, 0, cheepcheepnew_000_offset_002_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -33, -86, -35, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, cheepcheepnew_000_offset_003_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -34, 71, -36, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, cheepcheepnew_000_offset_004_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cheepcheepnew_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
