#include "src/game/envfx_snow.h"

const GeoLayout diplosaurus_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, diplosaurus_Bone_011_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, diplosaurus_Bone_015_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 40, -51, diplosaurus_Bone_015_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, diplosaurus_Bone_020_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 163, 37, diplosaurus_Bone_020_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 32, 137, 56, diplosaurus_arm_l_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, diplosaurus_arm2_l_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 14, -20, 8, diplosaurus_arm2_l_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -32, 137, 56, diplosaurus_arm_r_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, diplosaurus_arm2_r_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -14, -20, 8, diplosaurus_arm2_r_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, diplosaurus_thigh_l_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 52, 66, 28, diplosaurus_thigh_l_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, diplosaurus_leg_l_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -63, 0, diplosaurus_leg_l_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, diplosaurus_thigh_r_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -52, 66, 28, diplosaurus_thigh_r_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, diplosaurus_leg_r_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -63, 0, diplosaurus_leg_r_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, diplosaurus_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
