extern const GeoLayout tablebroken_geo[];
extern Lights1 tablebroken_f3d_material_005_lights;
extern u8 tablebroken_kibako_ci8[];
extern u8 tablebroken_kibako_ci8_pal_rgba16[];
extern Vtx tablebroken_Plane_024_mesh_layer_1_vtx_cull[8];
extern Vtx tablebroken_Plane_024_mesh_layer_1_vtx_0[47];
extern Gfx tablebroken_Plane_024_mesh_layer_1_tri_0[];
extern Gfx mat_tablebroken_f3d_material_005[];
extern Gfx mat_revert_tablebroken_f3d_material_005[];
extern Gfx tablebroken_Plane_024_mesh_layer_1[];
extern Gfx tablebroken_material_revert_render_settings[];
