extern const GeoLayout wariocarbroken_geo[];
extern Lights1 wariocarbroken_kart_body_f3d_lights;
extern Lights1 wariocarbroken_kart_tire_f3d_lights;
extern u8 wariocarbroken_kart_body_ci8[];
extern u8 wariocarbroken_kart_body_ci8_pal_rgba16[];
extern u8 wariocarbroken_kart_tire_ci8[];
extern u8 wariocarbroken_kart_tire_ci8_pal_rgba16[];
extern Vtx wariocarbroken_polygon1_mesh_layer_1_vtx_cull[8];
extern Vtx wariocarbroken_polygon1_mesh_layer_1_vtx_0[146];
extern Gfx wariocarbroken_polygon1_mesh_layer_1_tri_0[];
extern Vtx wariocarbroken_polygon1_mesh_layer_1_vtx_1[120];
extern Gfx wariocarbroken_polygon1_mesh_layer_1_tri_1[];
extern Gfx mat_wariocarbroken_kart_body_f3d[];
extern Gfx mat_revert_wariocarbroken_kart_body_f3d[];
extern Gfx mat_wariocarbroken_kart_tire_f3d[];
extern Gfx mat_revert_wariocarbroken_kart_tire_f3d[];
extern Gfx wariocarbroken_polygon1_mesh_layer_1[];
extern Gfx wariocarbroken_material_revert_render_settings[];
