#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/ccm/header.h"
#include "levels/ccm/geo.inc.c"


#include "levels/ccm/tireswing/geo.inc.c"
#include "levels/ccm/toybone/geo.inc.c"
#include "levels/ccm/floatboat/geo.inc.c"
#include "levels/ccm/MusclePengu/geo.inc.c"
#include "levels/ccm/sneakypengu/geo.inc.c"
#include "levels/ccm/smartpenguin/geo.inc.c"
#include "levels/ccm/bosspenguin/geo.inc.c"
#include "levels/ccm/chompgate/geo.inc.c"
#include "levels/ccm/table/geo.inc.c"
#include "levels/ccm/tablebroken/geo.inc.c"
#include "levels/ccm/zoobush/geo.inc.c"
#include "levels/ccm/zoobush2/geo.inc.c"
#include "levels/ccm/pinetreeNew/geo.inc.c"
#include "levels/ccm/wariocar/geo.inc.c"
#include "levels/ccm/waluigi/geo.inc.c"
#include "levels/ccm/wariogate/geo.inc.c"
#include "levels/ccm/pengucage/geo.inc.c"
#include "levels/ccm/wario/geo.inc.c"
#include "levels/ccm/dorrie/geo.inc.c"
#include "levels/ccm/sellguy/geo.inc.c"
#include "levels/ccm/banana/geo.inc.c"
#include "levels/ccm/wariocarbroken/geo.inc.c"
#include "levels/ccm/pengucannon/geo.inc.c"
#include "levels/ccm/blooper/geo.inc.c"
#include "levels/ccm/smolturtle/geo.inc.c"
#include "levels/ccm/sushinew/geo.inc.c"
#include "levels/ccm/mantanew/geo.inc.c"
#include "levels/ccm/cheepcheepnew/geo.inc.c"
#include "levels/ccm/penguplane/geo.inc.c"
#include "levels/ccm/skullblock/geo.inc.c"
#include "levels/ccm/spikeball/geo.inc.c"
#include "levels/ccm/fishbone/geo.inc.c"
#include "levels/ccm/enginepart/geo.inc.c"