#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/castle_grounds/header.h"

#include "levels/castle_grounds/geo.inc.c"

#include "levels/castle_grounds/submarine/geo.inc.c"
#include "levels/castle_grounds/bowsership/geo.inc.c"
#include "levels/castle_grounds/bowsernet/geo.inc.c"
#include "levels/castle_grounds/melon/geo.inc.c"
#include "levels/castle_grounds/apple/geo.inc.c"
#include "levels/castle_grounds/orange/geo.inc.c"
#include "levels/castle_grounds/stargate/geo.inc.c"
#include "levels/castle_grounds/N64logo/geo.inc.c"
#include "levels/castle_grounds/parakarry/geo.inc.c"
#include "levels/castle_grounds/floatwood/geo.inc.c"
#include "levels/castle_grounds/lilmouseOW/geo.inc.c"
#include "levels/castle_grounds/OWcrytals/geo.inc.c"
#include "levels/castle_grounds/bombomb/geo.inc.c"
#include "levels/castle_grounds/palmtree/geo.inc.c"
#include "levels/castle_grounds/seagull/geo.inc.c"
#include "levels/castle_grounds/warpshell/geo.inc.c"
#include "levels/castle_grounds/mechbowser/geo.inc.c"
#include "levels/castle_grounds/bowserfightgate/geo.inc.c"
#include "levels/castle_grounds/bowsercartOW/geo.inc.c"
#include "levels/castle_grounds/upcarpet/geo.inc.c"
#include "levels/castle_grounds/bounceball/geo.inc.c"
#include "levels/castle_grounds/fatyosher/geo.inc.c"