extern void scroll_castle_grounds_dl_CloudOcean_mesh_layer_5_vtx_0();
extern void scroll_sts_mat_castle_grounds_dl_OWWATER_layer5();
extern void scroll_castle_grounds_dl_CloudOcean_001_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds();
