extern const GeoLayout seesawplatform_geo[];
extern Lights1 seesawplatform_f3d_material_001_layer1_lights;
extern u8 seesawplatform__1e9be000_fmt0431_slice0_mip00_64x64_tm04_i4[];
extern u8 seesawplatform_Testmetooplz_i4[];
extern Vtx seesawplatform_Plane_mesh_layer_1_vtx_0[16];
extern Gfx seesawplatform_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_seesawplatform_f3d_material_001_layer1[];
extern Gfx mat_revert_seesawplatform_f3d_material_001_layer1[];
extern Gfx seesawplatform_Plane_mesh_layer_1[];
extern Gfx seesawplatform_material_revert_render_settings[];
