extern const GeoLayout lavarock3_geo[];
extern Lights1 lavarock3_f3d_material_lights;
extern u8 lavarock3_i8rzerztitziTxe_Ekaze2_rock_1_i8[];
extern Vtx lavarock3_Plane_003_mesh_layer_1_vtx_cull[8];
extern Vtx lavarock3_Plane_003_mesh_layer_1_vtx_0[24];
extern Gfx lavarock3_Plane_003_mesh_layer_1_tri_0[];
extern Gfx mat_lavarock3_f3d_material[];
extern Gfx mat_revert_lavarock3_f3d_material[];
extern Gfx lavarock3_Plane_003_mesh_layer_1[];
extern Gfx lavarock3_material_revert_render_settings[];
