extern const GeoLayout pinetreeNew_geo[];
extern Lights1 pinetreeNew_sm64_material_004_lights;
extern u8 pinetreeNew_pine_tree_rgba16_waifu2x_art_scale_tta_1_ci4[];
extern u8 pinetreeNew_pine_tree_rgba16_waifu2x_art_scale_tta_1_ci4_pal_rgba16[];
extern Vtx pinetreeNew_Circle_009_mesh_vtx_0[4];
extern Gfx pinetreeNew_Circle_009_mesh_tri_0[];
extern Gfx mat_pinetreeNew_sm64_material_004[];
extern Gfx mat_revert_pinetreeNew_sm64_material_004[];
extern Gfx pinetreeNew_Circle_009_mesh[];
extern Gfx pinetreeNew_material_revert_render_settings[];
