#include "src/game/envfx_snow.h"

const GeoLayout savestateYosh_ZZZZZZZZZZZ_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 71, 20, 1, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_mesh_mat_override_halfopen_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_Bone_005_skinned_mat_override_halfopen_0),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, 119, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_Bone_005_mesh_mat_override_halfopen_0),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, -18, 0, -38),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, -43, -46, 57),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_002_mesh_mat_override_halfopen_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_ZZZ_003_skinned_mat_override_halfopen_0),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 53, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_003_mesh_mat_override_halfopen_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout savestateYosh_ZZZZZZZZZZZ_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 71, 20, 1, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_mesh_mat_override_closed_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_Bone_005_skinned_mat_override_closed_1),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, 119, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_Bone_005_mesh_mat_override_closed_1),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, -18, 0, -38),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, -43, -46, 57),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_002_mesh_mat_override_closed_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_ZZZ_003_skinned_mat_override_closed_1),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 53, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_003_mesh_mat_override_closed_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout savestateYosh_ZZZZZZZZZZZ_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 71, 20, 1, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_mesh_mat_override_sad_2),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_Bone_005_skinned_mat_override_sad_2),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, 119, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_Bone_005_mesh_mat_override_sad_2),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, -18, 0, -38),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, -43, -46, 57),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_002_mesh_mat_override_sad_2),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_ZZZ_003_skinned_mat_override_sad_2),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 53, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_003_mesh_mat_override_sad_2),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout savestateYosh_ZZZZZZZZZZZ_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 71, 20, 1, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_mesh_mat_override_scared_3),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_Bone_005_skinned_mat_override_scared_3),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, 119, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_Bone_005_mesh_mat_override_scared_3),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, -18, 0, -38),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, -43, -46, 57),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_002_mesh_mat_override_scared_3),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_ZZZ_003_skinned_mat_override_scared_3),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 53, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_003_mesh_mat_override_scared_3),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout savestateYosh_ZZZZZZZZZZZ_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 71, 20, 1, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_mesh_mat_override_smug_flamboyant_4),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_Bone_005_skinned_mat_override_smug_flamboyant_4),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, 119, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_Bone_005_mesh_mat_override_smug_flamboyant_4),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, -18, 0, -38),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, -43, -46, 57),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_002_mesh_mat_override_smug_flamboyant_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_ZZZ_003_skinned_mat_override_smug_flamboyant_4),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 53, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_003_mesh_mat_override_smug_flamboyant_4),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout savestateYosh_ZZZZZZZZZZZ_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 71, 20, 1, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_mesh_mat_override_annoyed_5),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_Bone_005_skinned_mat_override_annoyed_5),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, 119, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_Bone_005_mesh_mat_override_annoyed_5),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, -18, 0, -38),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, -43, -46, 57),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_002_mesh_mat_override_annoyed_5),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_ZZZ_003_skinned_mat_override_annoyed_5),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 53, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_003_mesh_mat_override_annoyed_5),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout savestateYosh_ZZZZZZZZZZZ_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 71, 20, 1, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_mesh_mat_override_angry_6),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_Bone_005_skinned_mat_override_angry_6),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, 119, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_Bone_005_mesh_mat_override_angry_6),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, -18, 0, -38),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, -43, -46, 57),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_002_mesh_mat_override_angry_6),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_ZZZ_003_skinned_mat_override_angry_6),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 53, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_003_mesh_mat_override_angry_6),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout savestateYosh_ZZZZZZZZZZZ_opt8[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 71, 20, 1, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_mesh_mat_override_sleeping_7),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_Bone_005_skinned_mat_override_sleeping_7),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, 119, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_Bone_005_mesh_mat_override_sleeping_7),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, -18, 0, -38),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, -43, -46, 57),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_002_mesh_mat_override_sleeping_7),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_ZZZ_003_skinned_mat_override_sleeping_7),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 53, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_003_mesh_mat_override_sleeping_7),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout savestateYosh_ZZZZZZZZZZZ_opt9[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 71, 20, 1, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_mesh_mat_override_happy_8),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_Bone_005_skinned_mat_override_happy_8),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, 119, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_Bone_005_mesh_mat_override_happy_8),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, -18, 0, -38),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, -43, -46, 57),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_002_mesh_mat_override_happy_8),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_ZZZ_003_skinned_mat_override_happy_8),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 53, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_003_mesh_mat_override_happy_8),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout savestateYosh_ZZZZZZZZZZZ_opt10[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 71, 20, 1, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_mesh_mat_override_sunglasses_9),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_Bone_005_skinned_mat_override_sunglasses_9),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, 119, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_Bone_005_mesh_mat_override_sunglasses_9),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, -18, 0, -38),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, -43, -46, 57),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_002_mesh_mat_override_sunglasses_9),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_ZZZ_003_skinned_mat_override_sunglasses_9),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 53, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_003_mesh_mat_override_sunglasses_9),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout savestateYosh_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, -24, savestateYosh_AAAB_mesh),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 64, 0, 90, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, savestateYosh_AAAB_001_mesh),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 64, 0, savestateYosh_AAAC_mesh),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(11, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 71, 20, 1, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_Bone_005_skinned),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, 119, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_Bone_005_mesh),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, -18, 0, -38),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, -43, -46, 57),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_002_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_ZZZ_003_skinned),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 53, 0, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_ZZZ_003_mesh),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, savestateYosh_ZZZZZZZZZZZ_opt1),
					GEO_BRANCH(1, savestateYosh_ZZZZZZZZZZZ_opt2),
					GEO_BRANCH(1, savestateYosh_ZZZZZZZZZZZ_opt3),
					GEO_BRANCH(1, savestateYosh_ZZZZZZZZZZZ_opt4),
					GEO_BRANCH(1, savestateYosh_ZZZZZZZZZZZ_opt5),
					GEO_BRANCH(1, savestateYosh_ZZZZZZZZZZZ_opt6),
					GEO_BRANCH(1, savestateYosh_ZZZZZZZZZZZ_opt7),
					GEO_BRANCH(1, savestateYosh_ZZZZZZZZZZZ_opt8),
					GEO_BRANCH(1, savestateYosh_ZZZZZZZZZZZ_opt9),
					GEO_BRANCH(1, savestateYosh_ZZZZZZZZZZZ_opt10),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_arm1_l_skinned),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 56, 0, 22, -44, -90),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_arm1_l_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_arm2_l_skinned),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 0, -30, -1, -47),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_arm2_l_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_arm3_l_skinned),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 25, 0, 30, -17, -31),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_arm3_l_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_arm1_r_skinned),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 56, 0, 22, 44, 90),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_arm1_r_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_arm2_r_skinned),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 0, -30, 1, 47),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_arm2_r_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_arm3_r_skinned),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 25, 0, 30, 17, 31),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_arm3_r_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_atail_001_skinned),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 56, 0, -135, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 65, 0, 64, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, savestateYosh_atail_001_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, savestateYosh_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, savestateYosh_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
