extern const GeoLayout lavarock2_geo[];
extern Lights1 lavarock2_f3d_material_lights;
extern u8 lavarock2_i8rzerztitziTxe_Ekaze2_rock_1_i8[];
extern Vtx lavarock2_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx lavarock2_Plane_001_mesh_layer_1_vtx_0[14];
extern Gfx lavarock2_Plane_001_mesh_layer_1_tri_0[];
extern Gfx mat_lavarock2_f3d_material[];
extern Gfx mat_revert_lavarock2_f3d_material[];
extern Gfx lavarock2_Plane_001_mesh_layer_1[];
extern Gfx lavarock2_material_revert_render_settings[];
