#include "src/game/envfx_snow.h"

const GeoLayout martoise_geo[] = {
	GEO_CULLING_RADIUS(3500),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, martoise_Bone_mesh),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, martoise_Bone_002_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 500, 0, 103, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, martoise_Bone_002_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, martoise_Bone_003_skinned),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 1145, 0, -54, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, martoise_Bone_003_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, martoise_Bone_004_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 240, 0, 88, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, martoise_Bone_004_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, martoise_backflotte2_l_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 500, 0, -127, 17, -44),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 1259, 0, -2, 12, -25),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, martoise_backflotte2_l_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, martoise_backflotte3_l_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 350, 0, 15, -1, 12),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, martoise_backflotte3_l_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, martoise_backflotte2_r_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 500, 0, -127, -17, 44),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 1259, 0, -2, -12, 25),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, martoise_backflotte2_r_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, martoise_backflotte3_r_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 350, 0, 15, 1, -12),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, martoise_backflotte3_r_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, martoise_flotte2_l_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 500, 0, 125, 24, -1),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 922, 0, 25, 52, -43),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, martoise_flotte2_l_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, martoise_flotte3_l_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 628, 0, 15, -1, -2),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, martoise_flotte3_l_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, martoise_flotte2_r_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 500, 0, 125, -24, 1),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 922, 0, 25, -52, 43),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, martoise_flotte2_r_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, martoise_flotte3_r_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 628, 0, 15, 1, 2),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, martoise_flotte3_r_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, martoise_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
