extern const GeoLayout silverstara_geo[];
extern Lights1 silverstara_sm64_material_lights;
extern u8 silverstara__0302A6F0_i8[];
extern u8 silverstara__222_png_ia16[];
extern Vtx silverstara_Cube_mesh_vtx_cull[8];
extern Vtx silverstara_Cube_mesh_vtx_0[12];
extern Gfx silverstara_Cube_mesh_tri_0[];
extern Vtx silverstara_Cube_001_mesh_vtx_cull[8];
extern Vtx silverstara_Cube_001_mesh_vtx_0[4];
extern Gfx silverstara_Cube_001_mesh_tri_0[];
extern Gfx mat_silverstara_sm64_material[];
extern Gfx mat_revert_silverstara_sm64_material[];
extern Gfx mat_silverstara_sm64_material_002[];
extern Gfx mat_revert_silverstara_sm64_material_002[];
extern Gfx silverstara_Cube_mesh[];
extern Gfx silverstara_Cube_001_mesh[];
extern Gfx silverstara_material_revert_render_settings[];
