extern const GeoLayout crab_Bone_opt1[];
extern const GeoLayout crab_geo[];
extern Lights1 crab_f3d_material_lights;
extern Lights1 crab_f3d_material_001_lights;
extern u8 crab_ob_crab_1_ci8[];
extern u8 crab_ob_crab_1_ci8_pal_rgba16[];
extern u8 crab_ob_crab_2_ci8[];
extern u8 crab_ob_crab_2_ci8_pal_rgba16[];
extern Vtx crab_Bone_002_mesh_layer_4_vtx_0[4];
extern Gfx crab_Bone_002_mesh_layer_4_tri_0[];
extern Gfx mat_crab_f3d_material[];
extern Gfx mat_revert_crab_f3d_material[];
extern Gfx mat_crab_f3d_material_001[];
extern Gfx mat_revert_crab_f3d_material_001[];
extern Gfx crab_Bone_002_mesh_layer_4[];
extern Gfx crab_Bone_002_mesh_layer_4_mat_override_f3d_material_001_0[];
extern Gfx crab_material_revert_render_settings[];
