extern const GeoLayout wariocar_geo[];
extern Lights1 wariocar_kart_body_f3d_lights;
extern Lights1 wariocar_kart_tire_f3d_lights;
extern u8 wariocar_kart_body_ci8[];
extern u8 wariocar_kart_body_ci8_pal_rgba16[];
extern u8 wariocar_kart_tire_ci8[];
extern u8 wariocar_kart_tire_ci8_pal_rgba16[];
extern Vtx wariocar_polygon1_mesh_layer_1_vtx_cull[8];
extern Vtx wariocar_polygon1_mesh_layer_1_vtx_0[149];
extern Gfx wariocar_polygon1_mesh_layer_1_tri_0[];
extern Vtx wariocar_polygon1_mesh_layer_1_vtx_1[100];
extern Gfx wariocar_polygon1_mesh_layer_1_tri_1[];
extern Gfx mat_wariocar_kart_body_f3d[];
extern Gfx mat_revert_wariocar_kart_body_f3d[];
extern Gfx mat_wariocar_kart_tire_f3d[];
extern Gfx mat_revert_wariocar_kart_tire_f3d[];
extern Gfx wariocar_polygon1_mesh_layer_1[];
extern Gfx wariocar_material_revert_render_settings[];
