#include "src/game/envfx_snow.h"

const GeoLayout bbh_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Room1Layer1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Room1Layer4_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Room2Layer1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, bbh_dl_Room2Layer2_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Room2Layer4_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_Room2Layer5_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bbh_dl_Room2Layer6_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Room3Layer1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, bbh_dl_Room3Layer2_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Room3Layer4_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bbh_dl_Room3Layer6_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Room4Layer1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Room4Layer4_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Room5Layer1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Room5Layer4_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bbh_dl_Room5Layer6_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Room6Layer1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Room6Layer4_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Room7Layer1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Room7Layer4_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Room8Layer1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Room8Layer4_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Room9Layer1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Room9Layer4_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0043),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 75292, 0, -1, 75292, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bbh_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(0, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bbh_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
