extern const GeoLayout easterhead_geo[];
extern Lights1 easterhead_stone1_v4_lights;
extern Lights1 easterhead_stone2_v4_lights;
extern u8 easterhead_stone1_ci4[];
extern u8 easterhead_stone1_ci4_pal_rgba16[];
extern u8 easterhead_stone2_ci4[];
extern u8 easterhead_stone2_ci4_pal_rgba16[];
extern Vtx easterhead_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx easterhead_Cube_mesh_layer_1_vtx_0[81];
extern Gfx easterhead_Cube_mesh_layer_1_tri_0[];
extern Vtx easterhead_Cube_mesh_layer_1_vtx_1[112];
extern Gfx easterhead_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_easterhead_stone1_v4[];
extern Gfx mat_revert_easterhead_stone1_v4[];
extern Gfx mat_easterhead_stone2_v4[];
extern Gfx mat_revert_easterhead_stone2_v4[];
extern Gfx easterhead_Cube_mesh_layer_1[];
extern Gfx easterhead_material_revert_render_settings[];
