extern const GeoLayout tireswing_geo[];
extern Lights1 tireswing_taiya_png_f3d_lights;
extern Lights1 tireswing_f3d_material_023_lights;
extern u8 tireswing_taiya_i4[];
extern u8 tireswing_rope_ci8[];
extern u8 tireswing_rope_ci8_pal_rgba16[];
extern Vtx tireswing_taiya1_001_mesh_layer_1_vtx_0[62];
extern Gfx tireswing_taiya1_001_mesh_layer_1_tri_0[];
extern Vtx tireswing_taiya1_001_mesh_layer_1_vtx_1[28];
extern Gfx tireswing_taiya1_001_mesh_layer_1_tri_1[];
extern Gfx mat_tireswing_taiya_png_f3d[];
extern Gfx mat_revert_tireswing_taiya_png_f3d[];
extern Gfx mat_tireswing_f3d_material_023[];
extern Gfx mat_revert_tireswing_f3d_material_023[];
extern Gfx tireswing_taiya1_001_mesh_layer_1[];
extern Gfx tireswing_material_revert_render_settings[];
