extern void scroll_bitdw_dl_Layer1_003_mesh_layer_1_vtx_1();
extern void scroll_bitdw_dl_Layer1_008_mesh_layer_1_vtx_3();
extern void scroll_bitdw_dl_Layer1_011_mesh_layer_1_vtx_0();
extern void scroll_bitdw_dl_Layer1_012_mesh_layer_1_vtx_0();
extern void scroll_bitdw_dl_Layer1_013_mesh_layer_1_vtx_1();
extern void scroll_bitdw_dl_Layer1_013_mesh_layer_1_vtx_3();
extern void scroll_bitdw_dl_Layer6_mesh_layer_6_vtx_1();
extern void scroll_bitdw_dl_Layer1_026_mesh_layer_1_vtx_2();
extern void scroll_bitdw();
