#include "src/game/envfx_snow.h"

const GeoLayout boonard_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, boonard_Bone_mesh),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 50, 0, boonard_Bone_001_mesh),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, boonard_Bone_002_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 50, 0, -141, 40, 40),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, boonard_Bone_002_mesh),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 133, 0, -53, -36, 10),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, boonard_Bone_003_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, boonard_Bone_004_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 50, 0, -141, -40, -40),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, boonard_Bone_004_mesh),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, boonard_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, boonard_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
