extern const GeoLayout boonard_geo[];
extern Vtx boonard_Bone_mesh_vtx_0[6];
extern Gfx boonard_Bone_mesh_tri_0[];
extern Vtx boonard_Bone_mesh_vtx_1[46];
extern Gfx boonard_Bone_mesh_tri_1[];
extern Vtx boonard_Bone_mesh_vtx_2[6];
extern Gfx boonard_Bone_mesh_tri_2[];
extern Vtx boonard_Bone_mesh_vtx_3[8];
extern Gfx boonard_Bone_mesh_tri_3[];
extern Vtx boonard_Bone_001_mesh_vtx_0[31];
extern Gfx boonard_Bone_001_mesh_tri_0[];
extern Vtx boonard_Bone_002_mesh_vtx_0[1];
extern Gfx boonard_Bone_002_mesh_tri_0[];
extern Vtx boonard_Bone_002_skinned_vtx_0[3];
extern Gfx boonard_Bone_002_skinned_tri_0[];
extern Vtx boonard_Bone_003_mesh_vtx_0[18];
extern Gfx boonard_Bone_003_mesh_tri_0[];
extern Vtx boonard_Bone_004_mesh_vtx_0[1];
extern Gfx boonard_Bone_004_mesh_tri_0[];
extern Vtx boonard_Bone_004_skinned_vtx_0[3];
extern Gfx boonard_Bone_004_skinned_tri_0[];

extern Gfx boonard_Bone_mesh[];
extern Gfx boonard_Bone_001_mesh[];
extern Gfx boonard_Bone_002_mesh[];
extern Gfx boonard_Bone_002_skinned[];
extern Gfx boonard_Bone_003_mesh[];
extern Gfx boonard_Bone_004_mesh[];
extern Gfx boonard_Bone_004_skinned[];
extern Gfx boonard_material_revert_render_settings[];

