extern const GeoLayout seagull_Bone_opt1[];
extern const GeoLayout seagull_Bone_opt2[];
extern const GeoLayout seagull_Bone_opt3[];
extern const GeoLayout seagull_Bone_opt4[];
extern const GeoLayout seagull_Bone_opt5[];
extern const GeoLayout seagull_Bone_opt6[];
extern const GeoLayout seagull_Bone_opt7[];
extern const GeoLayout seagull_Bone_opt8[];
extern const GeoLayout seagull_geo[];
extern u8 seagull_Unbenannt_1_ia8[];
extern u8 seagull_Unbenannt_2_ia8[];
extern u8 seagull_Unbenannt_3_ia8[];
extern u8 seagull_Unbenannt_4_ia8[];
extern u8 seagull_Unbenannt_5_ia8[];
extern u8 seagull_Unbenannt_6_ia8[];
extern u8 seagull_Unbenannt_7_ia8[];
extern u8 seagull_Unbenannt_8_ia8[];
extern u8 seagull_Unbenannt_9_ia8[];
extern Vtx seagull_Bone_001_mesh_layer_4_vtx_0[4];
extern Gfx seagull_Bone_001_mesh_layer_4_tri_0[];
extern Gfx mat_seagull_F1[];
extern Gfx mat_revert_seagull_F1[];
extern Gfx mat_seagull_F2[];
extern Gfx mat_revert_seagull_F2[];
extern Gfx mat_seagull_F3[];
extern Gfx mat_revert_seagull_F3[];
extern Gfx mat_seagull_F4[];
extern Gfx mat_revert_seagull_F4[];
extern Gfx mat_seagull_F5[];
extern Gfx mat_revert_seagull_F5[];
extern Gfx mat_seagull_F6[];
extern Gfx mat_revert_seagull_F6[];
extern Gfx mat_seagull_F7[];
extern Gfx mat_revert_seagull_F7[];
extern Gfx mat_seagull_F8[];
extern Gfx mat_revert_seagull_F8[];
extern Gfx mat_seagull_F9[];
extern Gfx mat_revert_seagull_F9[];
extern Gfx seagull_Bone_001_mesh_layer_4[];
extern Gfx seagull_Bone_001_mesh_layer_4_mat_override_F2_0[];
extern Gfx seagull_Bone_001_mesh_layer_4_mat_override_F3_1[];
extern Gfx seagull_Bone_001_mesh_layer_4_mat_override_F4_2[];
extern Gfx seagull_Bone_001_mesh_layer_4_mat_override_F5_3[];
extern Gfx seagull_Bone_001_mesh_layer_4_mat_override_F6_4[];
extern Gfx seagull_Bone_001_mesh_layer_4_mat_override_F7_5[];
extern Gfx seagull_Bone_001_mesh_layer_4_mat_override_F8_6[];
extern Gfx seagull_Bone_001_mesh_layer_4_mat_override_F9_7[];
extern Gfx seagull_material_revert_render_settings[];
