extern const GeoLayout yoshiExclamationMark_Bone_opt1[];
extern const GeoLayout yoshiExclamationMark_Bone_opt2[];
extern const GeoLayout yoshiExclamationMark_Bone_opt3[];
extern const GeoLayout yoshiExclamationMark_Bone_opt4[];
extern const GeoLayout yoshiExclamationMark_Bone_opt5[];
extern const GeoLayout yoshiExclamationMark_geo[];
extern u8 yoshiExclamationMark_Cloud1_ci8[];
extern u8 yoshiExclamationMark_Cloud1_ci8_pal_rgba16[];
extern u8 yoshiExclamationMark_Cloud2_ci8[];
extern u8 yoshiExclamationMark_Cloud2_ci8_pal_rgba16[];
extern u8 yoshiExclamationMark_Cloud3_ci8[];
extern u8 yoshiExclamationMark_Cloud3_ci8_pal_rgba16[];
extern u8 yoshiExclamationMark_Cloud4_ci8[];
extern u8 yoshiExclamationMark_Cloud4_ci8_pal_rgba16[];
extern u8 yoshiExclamationMark_Cloud5_ci8[];
extern u8 yoshiExclamationMark_Cloud5_ci8_pal_rgba16[];
extern u8 yoshiExclamationMark_Cloud6_ci8[];
extern u8 yoshiExclamationMark_Cloud6_ci8_pal_rgba16[];
extern Vtx yoshiExclamationMark_Bone_001_mesh_layer_4_vtx_0[4];
extern Gfx yoshiExclamationMark_Bone_001_mesh_layer_4_tri_0[];
extern Gfx mat_yoshiExclamationMark_f3d_material_004[];
extern Gfx mat_revert_yoshiExclamationMark_f3d_material_004[];
extern Gfx mat_yoshiExclamationMark_f3d_material_005[];
extern Gfx mat_revert_yoshiExclamationMark_f3d_material_005[];
extern Gfx mat_yoshiExclamationMark_f3d_material_006[];
extern Gfx mat_revert_yoshiExclamationMark_f3d_material_006[];
extern Gfx mat_yoshiExclamationMark_f3d_material_007[];
extern Gfx mat_revert_yoshiExclamationMark_f3d_material_007[];
extern Gfx mat_yoshiExclamationMark_f3d_material_008[];
extern Gfx mat_revert_yoshiExclamationMark_f3d_material_008[];
extern Gfx mat_yoshiExclamationMark_f3d_material_009[];
extern Gfx mat_revert_yoshiExclamationMark_f3d_material_009[];
extern Gfx yoshiExclamationMark_Bone_001_mesh_layer_4[];
extern Gfx yoshiExclamationMark_Bone_001_mesh_layer_4_mat_override_f3d_material_005_0[];
extern Gfx yoshiExclamationMark_Bone_001_mesh_layer_4_mat_override_f3d_material_006_1[];
extern Gfx yoshiExclamationMark_Bone_001_mesh_layer_4_mat_override_f3d_material_007_2[];
extern Gfx yoshiExclamationMark_Bone_001_mesh_layer_4_mat_override_f3d_material_008_3[];
extern Gfx yoshiExclamationMark_Bone_001_mesh_layer_4_mat_override_f3d_material_009_4[];
extern Gfx yoshiExclamationMark_material_revert_render_settings[];
