#include "src/game/envfx_snow.h"

const GeoLayout shyguycaptain_geo[] = {
	GEO_CULLING_RADIUS(750),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, shyguycaptain_BODY_mesh_layer_5),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, shyguycaptain_Bone_004_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 83, 0, shyguycaptain_Bone_004_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, shyguycaptain_uparm_l_skinned_mesh_layer_5),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, 0, 0, -90),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 41, 0, 0, 0, -7),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, shyguycaptain_uparm_l_mesh_layer_5),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, shyguycaptain_lowerarm_l_skinned_mesh_layer_5),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 34, 0, 0, 0, -5),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, shyguycaptain_lowerarm_l_mesh_layer_5),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, shyguycaptain_lowerarm_l_mesh_layer_1),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 48, 0, 90, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, shyguycaptain_lowerarm_l_001_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_ALPHA, shyguycaptain_lowerarm_l_001_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, shyguycaptain_uparm_r_skinned_mesh_layer_5),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, 0, 0, 90),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 41, 0, 0, 0, 7),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, shyguycaptain_uparm_r_mesh_layer_5),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, shyguycaptain_lowerarm_r_skinned_mesh_layer_5),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 34, 0, 0, 0, 5),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, shyguycaptain_lowerarm_r_mesh_layer_5),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, shyguycaptain_lowerarm_r_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, shyguycaptain_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, shyguycaptain_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, shyguycaptain_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
