#include "src/game/envfx_snow.h"

const GeoLayout jokeUnagi_geo[] = {
	GEO_CULLING_RADIUS(6000),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(2000),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, jokeUnagi_000_offset_002_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 245, 0, 0, jokeUnagi_000_offset_002_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, jokeUnagi_000_offset_003_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 494, 0, 0, jokeUnagi_000_offset_003_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, jokeUnagi_000_offset_004_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 475, 0, 0, jokeUnagi_000_offset_004_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(2, geo_switch_anim_state),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, jokeUnagi_000_offset_005_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -254, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jokeUnagi_000_offset_005_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 527, 0, 0, jokeUnagi_000_offset_006_mesh_layer_4),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 226, 65, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, jokeUnagi_000_offset_008_mesh_layer_4),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jokeUnagi_001_offset_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 527, 0, 0, jokeUnagi_002_offset_002_mesh_layer_4),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, jokeUnagi_003_offset_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 527, 0, 0, jokeUnagi_003_offset_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 527, 0, 0, NULL),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, jokeUnagi_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, jokeUnagi_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
