extern const GeoLayout chompgate_geo[];
extern Lights1 chompgate_f3d_material_004_lights;
extern u8 chompgate_fuyuuAsibaAmiA_ia4[];
extern Vtx chompgate_Plane_018_mesh_layer_4_vtx_cull[8];
extern Vtx chompgate_Plane_018_mesh_layer_4_vtx_0[28];
extern Gfx chompgate_Plane_018_mesh_layer_4_tri_0[];
extern Gfx mat_chompgate_f3d_material_004[];
extern Gfx mat_revert_chompgate_f3d_material_004[];
extern Gfx chompgate_Plane_018_mesh_layer_4[];
extern Gfx chompgate_material_revert_render_settings[];
