extern const GeoLayout wallsword_geo[];
extern Lights1 wallsword_mt_sword_f3d_lights;
extern u8 wallsword_mt_sword_ci8[];
extern u8 wallsword_mt_sword_ci8_pal_rgba16[];
extern Vtx wallsword_Jolene_s_Sword_mesh_layer_1_vtx_0[32];
extern Gfx wallsword_Jolene_s_Sword_mesh_layer_1_tri_0[];
extern Gfx mat_wallsword_mt_sword_f3d[];
extern Gfx mat_revert_wallsword_mt_sword_f3d[];
extern Gfx wallsword_Jolene_s_Sword_mesh_layer_1[];
extern Gfx wallsword_material_revert_render_settings[];
