#include "levels/jrb/area_1/geo.inc.c"
#include "levels/jrb/area_2/geo.inc.c"
#include "levels/jrb/area_3/geo.inc.c"
#include "levels/jrb/area_4/geo.inc.c"
#include "levels/jrb/area_5/geo.inc.c"
#include "levels/jrb/area_6/geo.inc.c"
#include "levels/jrb/area_7/geo.inc.c"
#include "levels/jrb/area_0/geo.inc.c"
