extern const GeoLayout zoobush2_geo[];
extern Lights1 zoobush2_sm64_material_004_lights;
extern u8 zoobush2_potted_yucca_plant_ci4[];
extern u8 zoobush2_potted_yucca_plant_ci4_pal_rgba16[];
extern Vtx zoobush2_Circle_009_mesh_vtx_cull[8];
extern Vtx zoobush2_Circle_009_mesh_vtx_0[4];
extern Gfx zoobush2_Circle_009_mesh_tri_0[];
extern Gfx mat_zoobush2_sm64_material_004[];
extern Gfx mat_revert_zoobush2_sm64_material_004[];
extern Gfx zoobush2_Circle_009_mesh[];
extern Gfx zoobush2_material_revert_render_settings[];
