extern const GeoLayout bouncyflower_geo[];
extern Lights0 bouncyflower_sm64_material_044_lights;
extern Lights1 bouncyflower_sm64_material_045_lights;
extern u8 bouncyflower_bo9unceflower_ci4[];
extern u8 bouncyflower_bo9unceflower_ci4_pal_rgba16[];
extern Vtx bouncyflower_Plane_mesh_vtx_0[19];
extern Gfx bouncyflower_Plane_mesh_tri_0[];
extern Vtx bouncyflower_Plane_mesh_vtx_1[16];
extern Gfx bouncyflower_Plane_mesh_tri_1[];
extern Gfx mat_bouncyflower_sm64_material_044[];
extern Gfx mat_revert_bouncyflower_sm64_material_044[];
extern Gfx mat_bouncyflower_sm64_material_045[];
extern Gfx mat_revert_bouncyflower_sm64_material_045[];
extern Gfx bouncyflower_Plane_mesh[];
extern Gfx bouncyflower_material_revert_render_settings[];
