#include "src/game/envfx_snow.h"

const GeoLayout penguin_000_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, penguin_000_offset_006_mesh_layer_1_mat_override_eyes2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout penguin_000_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, penguin_000_offset_006_mesh_layer_1_mat_override_eyes3_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout penguin_000_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, penguin_000_offset_006_mesh_layer_1_mat_override_eyes4_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout penguin_000_switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, penguin_000_offset_006_mesh_layer_1_mat_override_eyes5_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout penguin_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 40, penguin_000_offset_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -51, 84, -13, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, penguin_000_offset_002_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 51, 84, -13, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, penguin_000_offset_003_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -38, -54, -13, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, penguin_000_offset_004_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 38, -54, -13, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, penguin_000_offset_005_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 111, -19, NULL),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(5, geo_switch_tuxie_mother_eyes),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, penguin_000_offset_006_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, penguin_000_switch_opt1),
							GEO_BRANCH(1, penguin_000_switch_opt2),
							GEO_BRANCH(1, penguin_000_switch_opt3),
							GEO_BRANCH(1, penguin_000_switch_opt4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, penguin_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
