extern const GeoLayout jellyblock_geo[];
extern Lights1 jellyblock_f3d_material_lights;
extern u8 jellyblock_blockface_ci8[];
extern u8 jellyblock_blockface_ci8_pal_rgba16[];
extern Vtx jellyblock_Cube_mesh_layer_5_vtx_0[24];
extern Gfx jellyblock_Cube_mesh_layer_5_tri_0[];
extern Gfx mat_jellyblock_f3d_material[];
extern Gfx mat_revert_jellyblock_f3d_material[];
extern Gfx jellyblock_Cube_mesh_layer_5[];
extern Gfx jellyblock_material_revert_render_settings[];
