#include "levels/jrb/texscroll.inc.h"
#include "levels/jrb/highlight/texscroll.inc.h"
#include "levels/jrb/TNT/texscroll.inc.h"
#include "levels/jrb/piranhavineswithint/texscroll.inc.h"
#include "levels/jrb/piranhavines/texscroll.inc.h"
#include "levels/jrb/NavalPiranha/texscroll.inc.h"
#include "levels/jrb/nipperkey/texscroll.inc.h"
#include "levels/jrb/nipperdoor/texscroll.inc.h"
#include "levels/jrb/boonard/texscroll.inc.h"
#include "levels/jrb/bridgepound/texscroll.inc.h"
#include "levels/jrb/minewall/texscroll.inc.h"
extern void scroll_textures_jrb();
