extern const GeoLayout pushshelf_geo[];
extern Lights1 pushshelf_f3d_material_065_lights;
extern Lights1 pushshelf_f3d_material_067_lights;
extern u8 pushshelf_th_hon00_ci8[];
extern u8 pushshelf_th_hon00_ci8_pal_rgba16[];
extern u8 pushshelf_Z_kai_main4_ci8[];
extern u8 pushshelf_Z_kai_main4_ci8_pal_rgba16[];
extern Vtx pushshelf_Plane_033_mesh_layer_1_vtx_0[4];
extern Gfx pushshelf_Plane_033_mesh_layer_1_tri_0[];
extern Vtx pushshelf_Plane_033_mesh_layer_1_vtx_1[15];
extern Gfx pushshelf_Plane_033_mesh_layer_1_tri_1[];
extern Gfx mat_pushshelf_f3d_material_065[];
extern Gfx mat_revert_pushshelf_f3d_material_065[];
extern Gfx mat_pushshelf_f3d_material_067[];
extern Gfx mat_revert_pushshelf_f3d_material_067[];
extern Gfx pushshelf_Plane_033_mesh_layer_1[];
extern Gfx pushshelf_material_revert_render_settings[];
