extern const GeoLayout pss_area_1_geo[];
extern const GeoLayout pss_area_1[];
extern const Collision pss_area_1_collision[];
extern const MacroObject pss_area_1_macro_objs[];
extern Lights1 pss_dl_f3d_material_008_lights;
extern Vtx pss_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx pss_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx pss_dl_Plane_001_mesh_layer_1_tri_0[];
extern Gfx mat_pss_dl_f3d_material_008[];
extern Gfx pss_dl_Plane_001_mesh_layer_1[];
extern Gfx pss_dl_material_revert_render_settings[];
