extern const GeoLayout icequad[];
extern Lights1 icequad_f3d_material_lights;
extern u8 icequad_SUPER_MARIO_64_84FED0D8_0_2_rgb_ci4[];
extern u8 icequad_SUPER_MARIO_64_84FED0D8_0_2_rgb_ci4_pal_rgba16[];
extern Vtx icequad_Circle_mesh_layer_7_vtx_0[7];
extern Gfx icequad_Circle_mesh_layer_7_tri_0[];
extern Gfx mat_icequad_f3d_material[];
extern Gfx mat_revert_icequad_f3d_material[];
extern Gfx icequad_Circle_mesh_layer_7[];
extern Gfx icequad_material_revert_render_settings[];
