#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/bbh/header.h"

#include "levels/bbh/geo.inc.c"

#include "levels/bbh/lightning/geo.inc.c"
#include "levels/bbh/ghostplatform/geo.inc.c"
#include "levels/bbh/ghostlantern/geo.inc.c"
#include "levels/bbh/destroybarrel/geo.inc.c"
#include "levels/bbh/booguybarrell/geo.inc.c"
#include "levels/bbh/floorbreak/geo.inc.c"
#include "levels/bbh/booguy/geo.inc.c"
#include "levels/bbh/jokeUnagi/geo.inc.c"
#include "levels/bbh/jellyblock/geo.inc.c"
#include "levels/bbh/paintguy/geo.inc.c"
#include "levels/bbh/wallsword/geo.inc.c"
#include "levels/bbh/tunnel/geo.inc.c"
#include "levels/bbh/tunnel2/geo.inc.c"
#include "levels/bbh/chandelier/geo.inc.c"
#include "levels/bbh/pushcargobox/geo.inc.c"
#include "levels/bbh/pushshelf/geo.inc.c"
#include "levels/bbh/ropebridge/geo.inc.c"
#include "levels/bbh/crumblefloor/geo.inc.c"
#include "levels/bbh/shyguyblock/geo.inc.c"
#include "levels/bbh/Shyguysays/geo.inc.c"
#include "levels/bbh/guybed/geo.inc.c"
#include "levels/bbh/movecrate/geo.inc.c"
#include "levels/bbh/rumbottle/geo.inc.c"
#include "levels/bbh/shyguycaptain/geo.inc.c"
#include "levels/bbh/fallplatform1/geo.inc.c"
#include "levels/bbh/fallplatform2/geo.inc.c"
#include "levels/bbh/lineplatform/geo.inc.c"