#include "src/game/envfx_snow.h"

const GeoLayout bitdw_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_006_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_007_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_008_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_009_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_010_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_011_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_012_mesh_layer_1),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, 90, 0, bitdw_dl_Layer1_013_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_014_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_015_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_016_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_017_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1_018_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_Layer1Unshaded_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_layer1UNTOUCH_mesh_layer_1),
		GEO_ROTATION_NODE_WITH_DL(LAYER_ALPHA, 0, 90, 0, bitdw_dl_Layer4_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitdw_dl_Layer4_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitdw_dl_Layer4_002_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitdw_dl_Layer4_003_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitdw_dl_Layer4_004_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitdw_dl_Layer4_005_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitdw_dl_Layer4_006_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitdw_dl_Layer4_007_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitdw_dl_Layer4_008_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitdw_dl_Layer4_009_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bitdw_dl_Layer6_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_mechabowser_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bitdw_dl_mechabowser_002_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bitdw_dl_ZGEARS_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bitdw_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -1, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bitdw_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_SNOW_NORMAL, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bitdw_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bitdw_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bitdw_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
