#include "src/game/envfx_snow.h"

const GeoLayout mantanew_geo[] = {
	GEO_CULLING_RADIUS(800),
	GEO_OPEN_NODE(),
		GEO_SCALE(LAYER_FORCE, 16384),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mantanew_000_offset_001_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, mantanew_000_offset_003_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 440, 220, 6, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mantanew_000_offset_003_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mantanew_000_offset_004_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 220, 0, 0, mantanew_000_offset_004_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, mantanew_000_offset_005_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 180, 0, 0, mantanew_000_offset_005_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, mantanew_000_offset_006_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 440, -220, 6, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mantanew_000_offset_006_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mantanew_000_offset_007_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 220, 0, 0, mantanew_000_offset_007_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, mantanew_000_offset_008_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 180, 0, 0, mantanew_000_offset_008_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mantanew_000_offset_010_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 168, 0, 0, mantanew_000_offset_010_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, mantanew_000_offset_011_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 236, 0, 0, mantanew_000_offset_011_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mantanew_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
