#include "src/game/envfx_snow.h"

const GeoLayout yoshimama_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshimama_Bone_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshimama_Bone_005_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 29, -75, yoshimama_Bone_005_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshimama_Bone_006_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 5, -76, yoshimama_Bone_006_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshimama_Bone_007_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 163, 0, yoshimama_Bone_007_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshimama_leg_l_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 77, 46, -18, yoshimama_leg_l_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshimama_leg_r_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -77, 46, -18, yoshimama_leg_r_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshimama_shoulder_l_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 48, 145, 1, yoshimama_shoulder_l_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshimama_arm_l_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 10, -36, 17, yoshimama_arm_l_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshimama_shoulder_r_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -48, 145, 1, yoshimama_shoulder_r_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshimama_arm_r_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -10, -36, 17, yoshimama_arm_r_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshimama_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
