extern const GeoLayout guybed_geo[];
extern Lights1 guybed_f3d_material_lights;
extern u8 guybed__3252176_ci4[];
extern u8 guybed__3252176_ci4_pal_rgba16[];
extern Vtx guybed_Plane_mesh_layer_4_vtx_cull[8];
extern Vtx guybed_Plane_mesh_layer_4_vtx_0[19];
extern Gfx guybed_Plane_mesh_layer_4_tri_0[];
extern Gfx mat_guybed_f3d_material[];
extern Gfx mat_revert_guybed_f3d_material[];
extern Gfx guybed_Plane_mesh_layer_4[];
extern Gfx guybed_material_revert_render_settings[];
