extern const GeoLayout pengucage_geo[];
extern Lights1 pengucage_f3d_material_lights;
extern u8 pengucage_fuyuuAsibaAmiA_ia4[];
extern Vtx pengucage_Cube_mesh_layer_4_vtx_cull[8];
extern Vtx pengucage_Cube_mesh_layer_4_vtx_0[12];
extern Gfx pengucage_Cube_mesh_layer_4_tri_0[];
extern Gfx mat_pengucage_f3d_material[];
extern Gfx mat_revert_pengucage_f3d_material[];
extern Gfx pengucage_Cube_mesh_layer_4[];
extern Gfx pengucage_material_revert_render_settings[];
