extern const GeoLayout lightning_geo[];
extern Lights1 lightning_f3d_material_lights;
extern u8 lightning_istockphoto_629835950_170667a_i8[];
extern Vtx lightning_Cube_mesh_layer_5_vtx_cull[8];
extern Vtx lightning_Cube_mesh_layer_5_vtx_0[4];
extern Gfx lightning_Cube_mesh_layer_5_tri_0[];
extern Gfx mat_lightning_f3d_material[];
extern Gfx mat_revert_lightning_f3d_material[];
extern Gfx lightning_Cube_mesh_layer_5[];
extern Gfx lightning_material_revert_render_settings[];
